### ISSUE TITLE
How can my BOT be online 24/7 ?

### ISSUE THREAD

**Issue by M-DinhHoangViet** [Torom/BotLi#106]
I want my BOT to stay online even though I turn off my computer

**Comment by Torom** [comment]
Then you have to run the bot somewhere else than on your computer.

**Comment by M-DinhHoangViet** [comment]
how to my Bot play faster

**Comment by Torom** [comment]
Is your bot losing on time or why should it play faster?

**Comment by M-DinhHoangViet** [comment]
> Bot của bạn thua đúng giờ hay tại sao nó phải chơi nhanh hơn?

yes, my BOT lose by time because play slow

**Comment by Torom** [comment]
It looks like you have massive internet problems. Your bot just stops playing after a few moves. Is your internet unstable? I guess there is not much you can do. The engine can only play if it has a connection to Lichess.

**Comment by M-DinhHoangViet** [comment]
Wifi is next to me. I think it's because the engine is slow or something needs to be done

**Comment by FatFritz2** [comment]
First if you want to make your bot play faster, you can use https://github.com/official-stockfish/Stockfish engine and add the UCI option called "Slow Mover" . I'd suggest you put it around 40-50 
Second you MUST leave your computer there to make the bot 24/7. Its exactly that you CANNOT turn off the PC and want the bot to run because it uses your pc's resources !
