### ISSUE TITLE
Auto rematch

### ISSUE THREAD

**Issue by EmptikBest** [Torom/BotLi#108]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
I would like it so I can configure the config.yml so it automatically sends a rematch to the bot it just played. This can be enchanced even further by there being options to only send a rematch if the bot win/draws/loses.

**Describe alternatives you've considered**
No alternatives.

**Additional context**
...

**Comment by Torom** [comment]
You would have to elaborate on why that would be useful. Always only one rematch or infinitely many?

**Comment by FatFritz2** [comment]
you can use `create` option in BotLi. There, you can choose how many games as you want !

**Comment by EmptikBest** [comment]
@Torom, I think the user should be able to configure how many rematches, or taking it even further by adding a option to send a number of rematches only if the bot wins/draws/loses. This would be useful in cases like, another bot defeats the bot, and then you want your bot to play against it again to try and win or something. I don't really know many use cases but there could be more.

In reply to your comment @FatFritz2, I know about the create option, but I just want my bot to challenge random players. I could use rematches in case of a scenario in which another bot draws my bot, and I want my bot to play more games with it, so I can know which bot is stronger. I also have both draw and resign disabled in my config.yml, since I want my bot to actually try to win a game, and if it doesn't, it can just lose, so the only draws are by threefold repetition and stalemate (which very rarely happens).

**Comment by Torom** [comment]
I don't like this idea for several reasons:

- I don't want features that are dependent on the game result. This only tempts to play more often against weaker bots etc.
- The feature would not work well with the matchmaking of other bots. Assuming the own bot is challenged as black (as it is usual for BotLi in matchmaking mode), then the rematch function proposed by you creates a rematch in the case as white, because it should be a rematch, so reversed colors. The other accepts the game, after this game the other continues his matchmaking and challenges you again to a game, you are then white again. So in the end your bot played two games as white and only one as black. Maybe the other bot has also activated the rematch function, then you play 4 instead of 2 games per matchmaking encounter. Then the color ratio is correct again, but still. That's not a big deal, but it is unpleasant.

**Comment by M-DinhHoangViet** [comment]
oh

**Comment by EmptikBest** [comment]
I agree with you now that I see it in that way @Torom, so I will close this

**Comment by EmptikBest** [comment]
@Torom I am re-opening this as I have another thing to say...

There can be a flag in the create command as for example `create 10 <bot> 1+1 true standard yes' where yes/no stands for rematch instead of challenge...

No options in config or anything, just so there is the 'View Rematch' button in the game page

**Comment by Torom** [comment]
I did not understand exactly what this option is supposed to do.

If you mean that no new challenge but a rematch should be offered, which the other can accept via the `rematch` button on the Lichess homepage. This is not possible with the bot API. There are no rematches available for bots.

**Comment by EmptikBest** [comment]
Oh okay, thanks for the quick response!

Yes I do mean that..

But can it be done with challenge:read, challenge:write, or/and challenge:bulk token??

**Comment by Torom** [comment]
No, rematches are not part of the [API](https://lichess.org/api).

**Comment by EmptikBest** [comment]
Okay, thanks... I might create a feature request in lichess-org/lila for this
