### ISSUE TITLE
Server/Network error

### ISSUE THREAD

**Issue by FatFritz2** [Torom/BotLi#111]
Hi @Torom,
In my BotLi for serveral days it keeps appearing 
`400 Client error Bad Request for url:` [game link]
and sometimes there are read timeout 1.0
I am wondering what error is that and how to fix it ???

**Comment by Torom** [comment]
This is not the complete error output. Probably network problems.

**Comment by FatFritz2** [comment]
So how can I resolve this 
It has been really hard to, can you give me some suggestions since my bot is losing on time quite a lot

**Comment by FatFritz2** [comment]
```
Book:    2.   Nf3         100 %
Book:    3.   Bb5          60 %
Book:    4.   O-O          75 %
Book:    5.   d4           75 %
Book:    6.   Bxc6        100 %
400 Client Error: Bad Request for url: https://lichess.org/api/bot/game/sbfQYCDM/move/b5c6?offeringDraw=false
Book:    7.   dxe5        100 %
Book:    8.   Qxd8+       100 %
Book:    9.   Nc3          40 %
Book:    10.  Rd1+         66 %
Book:    11.  h3           58 %
Book:    12.  Ne4          69 %
Book:    13.  Bf4          58 %
Book:    14.  b3           56 %
```
as you can see in the game it keeps appearing that error

**Comment by Torom** [comment]
BotLi gives moves one second to be sent to the server, if it takes longer, the move is sent again. In your case Lichess receives the move twice, which gives an error, because the move can't be executed twice. This is harmless in itself, but a sign that the move could not be sent to the server within a second.

If this happens frequently, your internet connection is not stable. BotLi cannot do anything about this. Maybe you should try to use a wired connection instead of WiFi.

**Comment by FatFritz2** [comment]
I have already trying ethernet (not wifi) but it keeps appearing that error
What can I do to fix ???

**Comment by Torom** [comment]
Again, BotLi can't do anything about your bad internet connection.
Increasing the `move_overhead_multiplier` increases the amount of time BotLi saves for such internet problems. You can try to set the value to `3.0`.
