### ISSUE TITLE
How to set up an opening book for botli in heroku 

### ISSUE THREAD

**Issue by aceventurapetdetective4** [Torom/BotLi#19]
how to setup a  cloud link to the relevent opening and setting to the directory

**Comment by Torom** [comment]
There are two options:

- You upload the book into your repository, then it is accessible for BotLi and you only have to change the `config.yml.default` accordingly.
- You download the book during the deployment. For that, you need to customize the Dockerfile and have it downloaded there. This would look similar to the line that downloads Stockfish from abrok. Also then the `config.yml.default` has to be adjusted accordingly.

**Comment by Torom** [comment]
I looked in your repository, you are making some mistakes there:

- `RUN wget https://zipproth.de/Brainfish/Cerebellum_Light_3Merge_200916.7z -O Cerebellum.zip` In this line you are trying to simply turn the .7z file into a .zip file, this cannot work. The line must look like this: `RUN wget https://zipproth.de/Brainfish/Cerebellum_Light_3Merge_200916.7z -O Cerebellum.7z`
- Since it is a .7z file, we need `p7zip` to handle it. So you have to add it in line 4. It should look like this: `RUN apt-get update && apt-get upgrade -y && apt-get install -y wget unzip python3 python3-pip p7zip`
- Now the archive has to be unpacked with the just installed p7zip. The line should look like this: `RUN 7zr e Cerebellum.7z && rm Cerebellum.7z`

Now you are done and the book is under the name 'Cerebellum3Merge.bin' in the directory of BotLi. Your `books` section in `config.yml.default` could then look like this:
```yml
books:
  Cerebellum3Merge: "Cerebellum3Merge.bin"
```

**Comment by aceventurapetdetective4** [comment]
thanks
