### ISSUE TITLE
Merging

### ISSUE THREAD

**Issue by FatFritz2** [Torom/BotLi#32]
How do I automatically update my repo I pulled request and what next then? please help
And how to make my bot don't get timed out quite often please alr tried bullet with incre

**Comment by Torom** [comment]
I think you need to resolve the conflicts first and then you can merge the pull request. You can do that on Github in the pull request.

Because of the losses on time, I'm not sure. Locally I have no problem with that at all, so it seems to be related to Heroku. Your `lichess_cloud` config doesn't make much sense. the `min_eval_depth` is way too high. So moves should never be played from the cloud? But anyway, that can`t be the reason for the losses on time.

**Comment by FatFritz2** [comment]
How to resolve the conflicts cuz Idk what are those conflicts

**Comment by Torom** [comment]
You could have googled that yourself: [https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github)

**Comment by FatFritz2** [comment]
Thanks I got merged rn
