### ISSUE TITLE
Exact Nodes and NPS

### ISSUE THREAD

**Issue by FatFritz2** [Torom/BotLi#71]
Hey @Torom,
I have an idea of forcing BotLi to list exact Node and Nps when playing like lichess bot
Thanks

**Comment by Torom** [comment]
What? Please try to explain what you mean.

**Comment by FatFritz2** [comment]
> What? Please try to explain what you mean.

I mean like you should try to get exact node and nodes per second of the bot

**Comment by Torom** [comment]
Exactly as opposed to what? What bothers you about them at the moment?

**Comment by FatFritz2** [comment]
U should try get exact node and nps like https://github.com/ShailChoksi/lichess-bot

**Comment by FatFritz2** [comment]
U didnt get what i mean lol

**Comment by EmptikBest** [comment]
I would also like this feature, but not exactly in this way... Instead of listing out exact number of nodes and nps in the cmd/eval command, it would be a good idea if that you are saving a logfile, which I mentioned in another question, it will display exact commands sent to the engine, exact nps and stuff like that for example... Only if possible, this is not a priority at all, also in the normal CMD it is not worth the additional clutter
